<?php

namespace App\Facades;

use Illuminate\Support\Facades\Facade;

class TicketRepository extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'ticket-repository'; // TODO: Change the autogenerated stub
    }
}
